In [2]:
# INIZIO PROGETTO
#importazione csv
import pandas as pd
df = pd.read_csv("wiki_movie_plots_deduped.csv")
df

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...
...,...,...,...,...,...,...,...,...
34881,2014,The Water Diviner,Turkish,Director: Russell Crowe,Director: Russell Crowe\r\nCast: Russell Crowe...,unknown,https://en.wikipedia.org/wiki/The_Water_Diviner,"The film begins in 1919, just after World War ..."
34882,2017,Çalgı Çengi İkimiz,Turkish,Selçuk Aydemir,"Ahmet Kural, Murat Cemcir",comedy,https://en.wikipedia.org/wiki/%C3%87alg%C4%B1_...,"Two musicians, Salih and Gürkan, described the..."
34883,2017,Olanlar Oldu,Turkish,Hakan Algül,"Ata Demirer, Tuvana Türkay, Ülkü Duru",comedy,https://en.wikipedia.org/wiki/Olanlar_Oldu,"Zafer, a sailor living with his mother Döndü i..."
34884,2017,Non-Transferable,Turkish,Brendan Bradley,"YouTubers Shanna Malcolm, Shira Lazar, Sara Fl...",romantic comedy,https://en.wikipedia.org/wiki/Non-Transferable...,The film centres around a young woman named Am...
34885,2017,İstanbul Kırmızısı,Turkish,Ferzan Özpetek,"Halit Ergenç, Tuba Büyüküstün, Mehmet Günsür, ...",romantic,https://en.wikipedia.org/wiki/%C4%B0stanbul_K%...,The writer Orhan Şahin returns to İstanbul aft...

In [3]:
# filtro colonne
df = df[['Genre', 'Plot']]
df

                 Genre                                               Plot
0              unknown  A bartender is working at a saloon, serving dr...
1              unknown  The moon, painted with a smiling face hangs ov...
2              unknown  The film, just over a minute long, is composed...
3              unknown  Lasting just 61 seconds and consisting of two ...
4              unknown  The earliest known adaptation of the classic f...
...                ...                                                ...
34881          unknown  The film begins in 1919, just after World War ...
34882           comedy  Two musicians, Salih and Gürkan, described the...
34883           comedy  Zafer, a sailor living with his mother Döndü i...
34884  romantic comedy  The film centres around a young woman named Am...
34885         romantic  The writer Orhan Şahin returns to İstanbul aft...

[34886 rows x 2 columns]

In [4]:
# print(df['Plot'].head())
# leggo uno specifico plot
plot1 = df.loc[1, 'Plot']
plot1

"The moon, painted with a smiling face hangs over a park at night. A young couple walking past a fence learn on a railing and look up. The moon smiles. They embrace, and the moon's smile gets bigger. They then sit down on a bench by a tree. The moon's view is blocked, causing him to frown. In the last scene, the man fans the woman with his hat because the moon has left the sky and is perched over her shoulder to see everything better."

In [5]:
# Guardo tutti i generi e il loro numero convertendo in dizionario
allgenres = df['Genre'].value_counts()
allgenres_dict = allgenres.to_dict()
allgenres_dict

{'unknown': 6083,
 'drama': 5964,
 'comedy': 4379,
 'horror': 1167,
 'action': 1098,
 'thriller': 966,
 'romance': 923,
 'western': 865,
 'crime': 568,
 'adventure': 526,
 'musical': 467,
 'crime drama': 464,
 'romantic comedy': 461,
 'science fiction': 418,
 'film noir': 345,
 'mystery': 310,
 'war': 273,
 'animation': 264,
 'comedy, drama': 236,
 'sci-fi': 221,
 'family': 217,
 'fantasy': 204,
 'animated': 195,
 'musical comedy': 154,
 'comedy-drama': 137,
 'biography': 136,
 'anime': 112,
 'suspense': 104,
 'romantic drama': 103,
 'comedy drama': 103,
 'animated short': 91,
 'drama, romance': 86,
 'social': 82,
 'historical': 77,
 'action thriller': 73,
 'documentary': 73,
 'serial': 71,
 'world war ii': 70,
 'family drama': 66,
 'war drama': 65,
 'drama, crime': 64,
 'comedy, musical': 63,
 'comedy/drama': 62,
 'comedy, romance': 60,
 'romance, drama': 58,
 'biopic': 57,
 'crime thriller': 56,
 'historical drama': 54,
 'black comedy': 52,
 'action comedy': 51,
 'comedy short': 50,
 'superhero': 48,
 'horror comedy': 47,
 'crime comedy': 47,
 'martial arts': 46,
 'action, drama': 46,
 'drama, biography': 46,
 'action, romance': 45,
 'drama, war': 44,
 'action, thriller': 43,
 'romance/comedy': 41,
 'social drama': 40,
 'melodrama': 39,
 'drama, adventure': 39,
 'romance/drama': 38,
 'action, comedy': 37,
 'action drama': 36,
 'biography, drama': 36,
 'drama, musical': 35,
 'comedy, family': 35,
 'drama, family': 35,
 'drama, thriller': 33,
 'mockumentary': 31,
 'comedy, crime': 31,
 'comedy / romance': 30,
 'short': 30,
 'drama / romance': 30,
 'romance, comedy': 29,
 ' ': 28,
 'tokusatsu': 28,
 'romance drama': 28,
 'spy': 27,
 'drama ': 27,
 'action, crime, drama': 27,
 'animated film': 25,
 'drama, comedy': 24,
 'dramedy': 24,
 'sports': 23,
 'drama, mystery': 22,
 'mythology': 22,
 'psychological thriller': 22,
 'action ': 21,
 'drama, action': 21,
 'biographical': 20,
 'action / drama': 20,
 'literary drama': 20,
 'action, sci-fi': 20,
 'family, fantasy': 20,
 'comedy, fantasy': 20,
 'sports drama': 20,
 'comedy, horror': 19,
 'spy/action': 19,
 'short subject': 19,
 'comedy ': 19,
 'drama, sports': 19,
 'romantic thriller': 18,
 'political thriller': 18,
 'romance / drama': 18,
 'thriller ': 18,
 'romance ': 17,
 'comedy, mystery': 17,
 'folklore': 17,
 'crime, drama': 16,
 'docudrama': 16,
 'crime/drama': 16,
 'costume drama': 16,
 'masala': 16,
 'family, drama': 16,
 'comedy/crime': 16,
 'action, crime': 16,
 'horror, thriller': 16,
 'action/drama': 16,
 'horror thriller': 16,
 'western comedy': 15,
 'comedy / drama': 15,
 'science-fiction': 15,
 'action / comedy': 14,
 'family film': 14,
 'action/thriller': 14,
 'drama, horror': 14,
 'animated feature': 14,
 'animated, family': 14,
 'war, drama': 14,
 'comedy, action': 14,
 'rom com': 14,
 'social family drama': 14,
 'action adventure': 14,
 'propaganda': 13,
 'musical drama': 13,
 'horror, comedy': 13,
 'action, science fiction': 13,
 'action/comedy': 13,
 'sex comedy': 13,
 'kaiju': 13,
 'action / crime': 13,
 'crime/thriller': 12,
 'slasher': 12,
 'action/romance': 12,
 'crime, comedy': 12,
 'comedy, thriller': 12,
 'comedy horror': 12,
 'sci-fi comedy': 12,
 'devotional': 12,
 'slapstick': 12,
 'drama/comedy': 12,
 'western, comedy': 12,
 'comedy/romance': 12,
 'disaster film': 11,
 'action, crime, drama, romance': 11,
 'comedy, sports': 11,
 'period drama': 11,
 'romantic-comedy': 11,
 'screwball comedy': 11,
 'mystery, thriller': 11,
 'action, horror': 11,
 'action masala': 11,
 'swashbuckler': 10,
 'comedy, science fiction': 10,
 'epic': 10,
 'disaster': 10,
 'war comedy': 10,
 'comedy/action': 10,
 'adventure, fantasy': 9,
 'action-adventure, fantasy': 9,
 'political drama': 9,
 'musical, comedy': 9,
 'comedy, drama, romance': 9,
 'wuxia': 9,
 'horror, romance, comedy': 9,
 'romance/thriller': 9,
 'action / romance': 9,
 'thriller drama': 9,
 'adventure, family': 9,
 'comedy thriller': 9,
 'musical/comedy': 9,
 'national film board animated short': 9,
 'sexploitation': 8,
 'drama / action': 8,
 'mystery, comedy': 8,
 'satire': 8,
 'comedy, western': 8,
 'comedy / action': 8,
 'biography, crime': 8,
 'suspense thriller': 8,
 'parody': 8,
 'drama, western': 8,
 'drama, social': 8,
 'action, fantasy': 8,
 'animation, family': 8,
 'drama, romance ': 8,
 'spy thriller': 8,
 'dark comedy': 8,
 'thriller, drama': 8,
 'comedy, teen': 8,
 'exploitation': 8,
 'action-comedy': 8,
 'supernatural horror': 8,
 'comedy, parody': 8,
 'romance / comedy': 8,
 'spy film': 7,
 'action, family': 7,
 'crime, action': 7,
 'musical, drama': 7,
 'drama/musical': 7,
 'historical/drama': 7,
 'action-masala': 7,
 'comedy/horror': 7,
 'action, adventure': 7,
 'adult': 7,
 "children's film": 7,
 'drama/thriller': 7,
 'comedy/musical': 7,
 'anthology': 7,
 'spy drama': 7,
 'romance/action': 7,
 'action, drama, family': 7,
 'romantic, drama': 7,
 'romantic': 7,
 'action, comedy, romance': 7,
 'western, biography': 7,
 'short film': 7,
 'fantasy drama': 7,
 'religious': 7,
 'children': 7,
 'bio-pic': 7,
 'adventure, drama': 7,
 'romance, thriller': 7,
 'detective': 7,
 'ero': 7,
 'african adventure': 6,
 'horror, suspense': 6,
 'romance, comedy, drama': 6,
 'animation, comedy': 6,
 'fantasy anime': 6,
 'bio-pic, drama': 6,
 'love': 6,
 'spy comedy': 6,
 'sports comedy': 6,
 'fantasy thriller': 6,
 'fantasy, romance': 6,
 'world war i': 6,
 'kung fu': 6,
 'action thriller ': 6,
 'martial arts / action': 6,
 'comedy romance': 6,
 'comedy, biography': 6,
 'drama / comedy': 6,
 'sci-fi, horror': 6,
 'musical, biography': 6,
 'musical, romance': 6,
 'historical epic': 6,
 'spy/thriller': 6,
 'crime, thriller': 6,
 'science fiction, thriller': 6,
 'horror/comedy': 6,
 'operetta': 5,
 'comedy film': 5,
 'horror / thriller': 5,
 'action-thriller': 5,
 'action-adventure': 5,
 'biker film': 5,
 'comedy mystery': 5,
 'animated, comedy, family': 5,
 'drama/action': 5,
 'biography, musical': 5,
 'horror, science fiction': 5,
 'comedy, drama, family': 5,
 'war/drama': 5,
 'fantasy romance': 5,
 'romance, action': 5,
 'prison drama': 5,
 'comedy western': 5,
 'science fiction, comedy': 5,
 'horror ': 5,
 'thriller, romance': 5,
 'drama/romance': 5,
 'tokusatsu, action, sci-fi': 5,
 'biblical drama': 5,
 'romance musical': 5,
 'psychological horror': 5,
 'war film': 5,
 'shakespearean': 5,
 'horror, sci-fi': 5,
 'history': 5,
 'action / martial arts': 5,
 'family, musical': 5,
 'action, comedy, drama': 5,
 'action, comedy, crime, drama': 5,
 'crime, horror': 5,
 'drama, romantic comedy': 5,
 'coming-of-age drama': 5,
 'science fiction comedy': 5,
 'drama / action / crime': 5,
 'horror / comedy': 5,
 'drama film': 5,
 'thriller/drama': 5,
 'sports/comedy': 5,
 'crime / thriller': 5,
 'supernatural thriller': 5,
 'political': 5,
 'world war ii comedy': 4,
 'teen comedy': 4,
 'drama/biographical': 4,
 'short drama': 4,
 'action / martial arts / comedy': 4,
 'world war ii/pow': 4,
 'science fiction, horror': 4,
 'yakuza': 4,
 'adventure, comedy': 4,
 'fantasy, thriller': 4,
 'romance, comedy, horror': 4,
 'drama, romance, slice of life': 4,
 'gangster': 4,
 'mystery, horror': 4,
 'national film board documentary': 4,
 'comedy-drama, romance': 4,
 'world war ii/drama': 4,
 'erotic thriller': 4,
 'comedy/thriller': 4,
 'biblical': 4,
 'drama, fantasy': 4,
 'science fiction anime': 4,
 'slasher film': 4,
 'drama, science fiction': 4,
 'dance': 4,
 'adult comedy': 4,
 'action, crime drama': 4,
 'rom-com': 4,
 'action / thriller': 4,
 'action / kung fu / comedy': 4,
 'crime, drama, thriller': 4,
 'comedy, adventure': 4,
 'action / adventure': 4,
 'comedy / horror': 4,
 'neo-noir': 4,
 'pink': 4,
 'satire, drama': 4,
 'comedy, satire': 4,
 'socio-fantasy': 4,
 'biography, war': 4,
 'thriller, action': 4,
 'short comedy': 4,
 'romantic comedy ': 4,
 'satirical comedy': 4,
 'adventure serial': 4,
 'comedy / fantasy': 4,
 'biographical drama': 4,
 'drama / crime': 4,
 'comedy-thriller': 4,
 'christian': 4,
 'supernatural': 4,
 'espionage': 4,
 'experimental': 4,
 'biographical, drama': 4,
 'suspense / thriller': 4,
 'fantasy, adventure': 4,
 'suspense, thriller': 4,
 'family, live-action': 4,
 'action romance': 4,
 'action/adventure': 4,
 'sword': 4,
 'sci-fi, comedy': 4,
 'war, biography': 4,
 'horror, drama': 4,
 'samurai film': 4,
 'dramatic comedy': 4,
 'romance / action': 4,
 'romance action': 4,
 'costume': 4,
 'sci-fi horror': 4,
 '-': 3,
 'comedy, drama, musical': 3,
 'mystery/thriller': 3,
 'action, masala': 3,
 'musical/romance': 3,
 'musical/drama': 3,
 'roman porno': 3,
 'drama-thriller': 3,
 'anime fantasy': 3,
 'romance, war': 3,
 'horror, mystery': 3,
 'animation comedy': 3,
 'western, musical': 3,
 'science fiction, mystery': 3,
 'animation adventure': 3,
 'erotic / drama': 3,
 'action/romance/comedy': 3,
 'superhero action adventure': 3,
 'sci-fi for children': 3,
 'supernatural/action/anime': 3,
 'costume action': 3,
 'drama / comedy / romance': 3,
 'dance, drama': 3,
 'crime / drama': 3,
 'drama romance': 3,
 'music': 3,
 'action & romance': 3,
 'fantasy/adventure': 3,
 'drama / thriller': 3,
 'action, spy film': 3,
 'biopic, drama': 3,
 'heist': 3,
 'fantasy adventure': 3,
 'political satire': 3,
 'western drama': 3,
 'thriller, fantasy': 3,
 'science fiction, action': 3,
 'anime for children': 3,
 'action / crime / drama': 3,
 'crime, drama, mystery': 3,
 'anthology, horror': 3,
 'social romance': 3,
 'drama, romance, thriller': 3,
 'action, war': 3,
 'comedy, drama, romance ': 3,
 'comedy, romance, musical': 3,
 'drama, epic': 3,
 'thriller romance': 3,
 'nfb animated short': 3,
 'animated, comedy': 3,
 'action, drama, romance': 3,
 'family comedy': 3,
 'romantic musical': 3,
 'adult film': 3,
 'drama, music': 3,
 'action / adventure / martial arts': 3,
 'comedy, romance ': 3,
 'historical, fantasy, adventure, action, science fantasy, superheroes': 3,
 'science fiction, drama': 3,
 'romantic comedy, drama': 3,
 'sci-fi fantasy': 3,
 'thriller, mystery': 3,
 'horror, musical': 3,
 'drama, thriller ': 3,
 'adventure drama': 3,
 'historical, drama': 3,
 'romantic fantasy': 3,
 'drama, social ': 3,
 'musical fantasy': 3,
 'action, crime, drama, thriller': 3,
 'sci-fi drama': 3,
 'horror drama': 3,
 'family, comedy': 3,
 'animated comedy': 3,
 'action, crime, romance': 3,
 'historical/action': 3,
 'true crime': 3,
 'spy film, comedy': 3,
 'drama / family': 3,
 'mystery / thriller': 3,
 'biography, sports': 3,
 'horror, psychological thriller, drama, dark fantasy': 3,
 'romance, action, comedy': 3,
 'social family': 3,
 'crime/romance': 3,
 'war, comedy': 3,
 'action / fantasy': 3,
 'war, action': 3,
 'action, romance, drama': 3,
 'drama/history': 3,
 'fantasy, comedy': 3,
 'action / crime / thriller': 3,
 'drama / mystery / crime': 3,
 'comedy/satire': 3,
 'educational': 3,
 'imdb': 2,
 'romantic family drama': 2,
 'crime/action': 2,
 'family, thriller': 2,
 'action, thriller, romance, drama, comedy': 2,
 'war/historical': 2,
 'action / crime / adventure': 2,
 'fantasy / romance / action': 2,
 'biography, crime, drama': 2,
 'romance / fantasy': 2,
 'drama / history': 2,
 'fantasy / adventure': 2,
 'comedy / action / adventure': 2,
 'horror, romance': 2,
 'action / martial arts / costume': 2,
 'drama / mystery': 2,
 'portmanteau horror': 2,
 'biography, war, drama': 2,
 'animation / fantasy / adventure': 2,
 'drama, family, romance': 2,
 'comedy / romance / fantasy': 2,
 'romance thriller': 2,
 'sci-fi / action': 2,
 'comedy / action / fantasy': 2,
 'thriller, western': 2,
 'social thriller': 2,
 'thriller / horror': 2,
 'family, drama, romance': 2,
 'animated, superhero': 2,
 'remake': 2,
 'horror comedy, parody': 2,
 'super hit movie': 2,
 'mythological': 2,
 'fiction': 2,
 'romance / suspense': 2,
 'drama, mystery, thriller': 2,
 'drama / sports': 2,
 'horror, mystery, thriller': 2,
 'horror / drama': 2,
 'action, crime, drama, family': 2,
 'comedy, drama, romance, family': 2,
 'romance, comedy, thriller': 2,
 'thriller, horror': 2,
 'medical thriller': 2,
 'comedy / mystery': 2,
 'action / drama / crime': 2,
 'comedy / fantasy / adventure / costume': 2,
 'comedy-horror': 2,
 'politics': 2,
 'action, adventure, fantasy, sci-fi': 2,
 'drama / action / fantasy / adventure': 2,
 'drama / action / martial arts / costume': 2,
 'supernatural comedy': 2,
 'action / comedy / crime': 2,
 'action / comedy / drama': 2,
 'adventure / comedy': 2,
 'yash raj films': 2,
 'action / adventure / comedy': 2,
 'spy/comedy': 2,
 'comedy, drama ': 2,
 'comedy/western': 2,
 'action/crime': 2,
 'action, romance ': 2,
 'crime thriller romance': 2,
 'crime, thriller ': 2,
 'crime romance': 2,
 'gangster drama': 2,
 'comedy, romance, drama': 2,
 'african drama': 2,
 'action / crime / comedy': 2,
 'thriller comedy': 2,
 'biopic drama': 2,
 'gun fu': 2,
 'historical fiction': 2,
 'slapstick comedy': 2,
 'costume action adventure': 2,
 'animated short co-produced with the national film board': 2,
 'socio-political': 2,
 'sci-fi/comedy': 2,
 'futuristic drama': 2,
 'adult/comedy': 2,
 'romantic/comedy': 2,
 'adult/horror': 2,
 'thriller/horror': 2,
 'suspense/thriller': 2,
 'adult/thriller': 2,
 'drama, musical, romance': 2,
 'world war ii/adventure': 2,
 'period': 2,
 'animated/adventure': 2,
 'romance comedy': 2,
 'horror, comedy, romance': 2,
 'horror / romance / comedy': 2,
 'drama, romance, thriller, musical': 2,
 'australian western': 2,
 'biographical/historical': 2,
 'zombie horror': 2,
 'biodrama': 2,
 'horror, fantasy, adventure': 2,
 'social satire': 2,
 'romance, drama, musical': 2,
 'anthology film': 2,
 'comedy / crime': 2,
 'tragedy': 2,
 'biopic devotional': 2,
 'erotic drama': 2,
 'family, adventure': 2,
 "children's": 2,
 'comedy / thriller': 2,
 'drama action': 2,
 'romance / thriller': 2,
 'romantic action': 2,
 'family social': 2,
 'science fiction film': 2,
 'romance, drama, comedy': 2,
 'children drama': 2,
 'shakespearean drama': 2,
 'gangster film': 2,
 'drama, romance, musical ': 2,
 'police drama': 2,
 'romance comedy drama': 2,
 'social crime': 2,
 'war/romance': 2,
 'fantasy, drama': 2,
 'mystery/horror': 2,
 'zombie comedy': 2,
 'comedy, family film': 2,
 'martial arts / action / comedy': 2,
 'romance/musical': 2,
 'action / kung fu': 2,
 'boxing drama': 2,
 'social/drama': 2,
 'family romance': 2,
 'animated, adult': 2,
 'biker': 2,
 'socio-fantasy, comedy': 2,
 'spy serial': 2,
 'propaganda short': 2,
 'crime, family': 2,
 'historical, fantasy, drama, jidaigeki, action': 2,
 'western, horror': 2,
 'detective fiction, drama': 2,
 'historical, action, military, spy, superheroes': 2,
 'musical, family': 2,
 'action, samurai film': 2,
 'j-horror': 2,
 "fantasy, drama, children's, action, comedy": 2,
 'historical film': 2,
 'action, 007': 2,
 'musical, fantasy': 2,
 'drama, comedy-drama, slice of life': 2,
 'horror, action': 2,
 'animated, musical': 2,
 'charlie chan': 2,
 'action, superhero': 2,
 'family, animated': 2,
 'thriller, comedy': 2,
 "drama, children's, romance, slice of life, sci-fi, youth": 2,
 'blaxploitation': 2,
 'musical romance': 2,
 'science fiction thriller': 2,
 'sci-fi, drama': 2,
 'adventure, animated': 2,
 'drama, biopic': 2,
 'legal drama': 2,
 'drama, mecha, sci-fi, adventure, spy': 2,
 'western serial': 2,
 'action-adventure, family': 2,
 'drama, romance, action': 2,
 'christian drama': 2,
 'romantic comedy, teen': 2,
 'action western': 2,
 'action & love': 2,
 'epic, biography': 2,
 'comedy-drama, romantic comedy, youth, science fantasy': 2,
 'family, live-action/animated film': 2,
 'sports (shogi, chess), comedy-drama': 2,
 'animated musical': 2,
 'avant-garde, drama': 2,
 'p.o.w.': 2,
 'fantasy, action, science fantasy': 2,
 'kaiju eiga': 2,
 'jidaigeki': 2,
 'chambara': 2,
 'samurai': 2,
 'comedy, road': 2,
 'war romance': 2,
 'buddy cop, comedy': 2,
 'action for children': 2,
 'action comedy, superhero': 2,
 'comedy, superhero': 2,
 'fantasy, anime': 2,
 'animated, war': 2,
 'nature documentary': 2,
 'action - romance': 2,
 'horror, western': 2,
 'comedy, short': 2,
 'animated, short': 2,
 'dramedy, thriller': 2,
 'fantasy, science fiction': 2,
 'dance, drama, romance': 2,
 'western, serial': 2,
 'avant-garde, horror': 2,
 'sci-fi, thriller': 2,
 'action, romantic comedy': 2,
 'action thriller, science fiction': 2,
 'sci-fi, action': 2,
 'drama[not in citation given]': 2,
 'mystery, drama': 2,
 'thriller, crime': 2,
 'adventure, thriller': 2,
 'fairy tale': 2,
 'comedy-drama, slice of life, sci-fi': 2,
 'murder mystery': 2,
 'comedy action': 2,
 'political, drama, crime, mystery, thriller': 2,
 'teen': 2,
 'horror / mystery': 2,
 'avant-garde': 2,
 'western, war': 2,
 'action, biography': 2,
 'road thriller': 2,
 'superhero, action': 2,
 'horror, slasher': 2,
 'musical biography': 2,
 'drama, action, sci-fi, comedy': 2,
 'action comedy, family': 2,
 'biography, comedy': 2,
 'drama, comedy, action': 2,
 'drama, coming of age': 2,
 'adventure, action': 2,
 'crime drama, action': 2,
 'historical biopic': 2,
 'drama, exploitation': 2,
 'comedy, drama film': 2,
 'family adventure': 2,
 'drama, action, spy, sci-fi, superheroes, tokusatsu': 2,
 'horror, dark fantasy, drama, supernatural horror, action, monster': 2,
 'historical comedy': 2,
 'horror, thriller, supernatural': 2,
 'action, drama, adventure, crime': 1,
 'drama, romance, thriller ': 1,
 'action, drama, romance ': 1,
 'romance, fantasy, musical ': 1,
 'drama, romance, comedy, family, musical, social ': 1,
 'family, crime, drama': 1,
 'drama, romance, comedy, musical ': 1,
 'drama, family, musical': 1,
 'action, adventure, crime': 1,
 'horror, thriller ': 1,
 'action, drama, horror': 1,
 'drama, musical ': 1,
 'action, drama, romance, thriller ': 1,
 "drama, youth, sports (children's poker, karuta)": 1,
 'drama, comedy, action, spy, sci-fi, superheroes': 1,
 'action, adventure, comedy, drama, science fiction, musical, fantasy': 1,
 'fantasy, drama, romance, slice of life': 1,
 'adventure, mystery, thriller': 1,
 'drama, musical, social': 1,
 'drama, family, action': 1,
 'adventure, crime, romance': 1,
 'action, adventure, drama, romance, family': 1,
 'drama, tokusatsu, action, sci-fi': 1,
 'historical, drama, action, superheroes, spy, sci-fi': 1,
 'comedy, drama, horror': 1,
 'historical, psychological thriller, black comedy, dark fantasy, science fantasy': 1,
 'war, drama, action, romance': 1,
 'action, crime, musical': 1,
 'action, musical, drama, comedy': 1,
 'drama, action, sci-fi, spy': 1,
 'drama, romance, family, musical': 1,
 'drama, crime, family': 1,
 'comedy, romance, social': 1,
 'horror comedy, horror, drama, monster': 1,
 'drama, romance, crime': 1,
 'fantasy, action, adventure, science fantasy, sci-fi, superheroes': 1,
 'dance, idol, magical girl, musical': 1,
 'adult drama': 1,
 'comedy, romance, drama, musical': 1,
 'action, adventure, drama, musical, family': 1,
 'horror, post-apocalyptic, steampunk, action': 1,
 'horror, post-apocalyptic, steampunk, spy, action': 1,
 'romance, sport': 1,
 'war, drama, historical ': 1,
 'comedy, musical, romance, family': 1,
 'drama, youth, musical': 1,
 'romance, drama, comedy ': 1,
 'crime fiction, drama, historical': 1,
 'action, comedy, drama, romance': 1,
 'fantasy, action, adventure': 1,
 'family, musical, romance': 1,
 'comedy, social, musical ': 1,
 'action, adventure, romance': 1,
 'political, fantasy, drama, mystery, thriller': 1,
 'fantasy, drama, comedy, mystery': 1,
 'horror, drama, action, sci-fi': 1,
 'fantasy, action, science fantasy, sci-fi': 1,
 'family, romance, drama': 1,
 'drama, action, comedy, crime': 1,
 'fantasy, drama, romance, sci-fi': 1,
 'romance, drama,': 1,
 'drama, comedy, romance, action, superheroes, spy': 1,
 'nadeem-shravan': 1,
 'romance, action, thriller': 1,
 'social, war, action': 1,
 'thriller, romance, musical': 1,
 'family, crime, drama, romance': 1,
 'romance, crime': 1,
 'romance, action, drama': 1,
 'romance, drama, comedy, musical': 1,
 'drama, fantasy, family, thriller': 1,

In [6]:
# Filtro il dataset tenendo solo 4 generi
selected_genres = ['drama', 'comedy', 'horror', 'action']
df = df[df['Genre'].isin(selected_genres)].copy()
print(df['Genre'].value_counts())
df

Genre
drama     5964
comedy    4379
horror    1167
action    1098
Name: count, dtype: int64

        Genre                                               Plot
7      comedy  The film is about a family who move to the sub...
14     comedy  Before heading out to a baseball game at a nea...
15     comedy  The plot is that of a black woman going to the...
16      drama  On a beautiful summer day a father and mother ...
17      drama  A thug accosts a girl as she leaves her workpl...
...       ...                                                ...
34874   drama  Hasan is a twelve-year-old boy living with his...
34875   drama  Through the night, three cars carry a small gr...
34876   drama  The film opens with a Senegalese boy named Kha...
34882  comedy  Two musicians, Salih and Gürkan, described the...
34883  comedy  Zafer, a sailor living with his mother Döndü i...

[12608 rows x 2 columns]

In [7]:
df_bilanciato = (
    df.groupby('Genre')
    .apply(lambda x: x.sample(n=1100, random_state=42) if len(x) > 1100 else x)
    .reset_index(drop=True)
)

# mescola le righe
df_bilanciato = df_bilanciato.sample(frac=1, random_state=42).reset_index(drop=True)


#  Visualizza un riepilogo
print(df_bilanciato['Genre'].value_counts())
df_bilanciato

Genre
comedy    1100
drama     1100
horror    1100
action    1098
Name: count, dtype: int64

C:\Users\sissi\AppData\Local\Temp\ipykernel_29036\130722243.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=1100, random_state=42) if len(x) > 1100 else x)

       Genre                                               Plot
0     comedy  Sir Sidney Ruff-Diamond (Sid James) is Queen V...
1     comedy  Three plots in three different historical peri...
2      drama  A Canadian mother and businesswoman Dinah Midd...
3     horror  At the Yucca Mountain nuclear waste repository...
4     comedy  Leonard Hoffman is a Los Angeles insurance age...
...      ...                                                ...
4393  horror  William Edward "Billy" Lenz, a boy born with s...
4394  action  Alcoholic U.S. Air Marshal Bill Marks boards a...
4395   drama  Judge Ross, on the Federal Bench, rules in fav...
4396  horror  A year later in 1906, following the events of ...
4397  action  The story revolves around an ego clash between...

[4398 rows x 2 columns]

In [104]:
import re

# definisco una funzione che pulisca i testi
def pulisci_testo(text):
    text = text.lower()                      # minuscolo
    text = re.sub(r'\d+', '', text)          # rimuove numeri
    text = re.sub(r'[^\w\s]', '', text)      # rimuove punteggiatura
    text = text.strip()                      # rimuove spazi ai bordi
    return text

In [ ]:
# applico la funzione a 3 testi e vedo il confronto originale/pulito
for i in range(1, 4):
    original = df_bilanciato.loc[i, 'Plot']
    cleaned = pulisci_testo(original)
    print(f"Plot {i}:\n")            # f sta per formatted string
    print("Originale:", original)
    print("Pulito:", cleaned)
    print()  # Riga vuota

Plot 1:

Originale: Three plots in three different historical periods—prehistoric times, Ancient Rome, and modern times (the Roaring Twenties)—are intercut to prove the point that man's love for woman has not significantly changed throughout history. In all three plots, characters played by the small and slight Buster Keaton and handsome bruiser Wallace Beery compete for the attention of the same woman, played by Margaret Leahy. Each plot follows similar "arcs" in the story line in which Keaton's character works for his beloved's attention and eventually wins her over.
In the Stone Age story line, Keaton competes with the bigger, brutish Beery for a cavewoman Leahy. After observing another caveman drag away a woman by the hair in order to "claim" her, Keaton tries to become more assertive, but is continuously pushed back and bullied by Beery. An attempt to make Leahy jealous by flirting with another woman ends in failure. Nevertheless, Keaton grows closer to Leahy, and Beery challenges him to a fight at sunrise. Keaton wins thanks to hiding a rock in his club, but is caught and tied to the tail of an elephant to be dragged around the dirt as punishment. Upon his return, he finds Leahy about to be claimed by Beery and attempts to make off with her. Beery catches him and the two battle by tossing boulders at each other from afar, with Keaton and Leahy on a cliff together. When Beery climbs up to reclaim Leahy, Keaton dispatches Leahy's cronies and finally defeats him. He drags a smitten Leahy off by the hair. In the epilogue, they go off for a walk with their huge family of children following them.
In the Ancient Rome segment, Keaton attempts to attract the attention of the wealthy Leahy, but is continually pushed back by Beery. Beery challenges him to a chariot race after a hard snow — Keaton wins by using sled dogs instead of horses. In revenge, Beery forces him into the lion pit belonging to Leahy's family. Keaton survives by befriending the lion and cleaning its claws. Keaton is rescued by Leahy's parents while Beery kidnaps Leahy. Keaton rescues her and tries to seduce her in her palanquin, which takes off without them. In the epilogue, they also go out for a walk with many children in tow.
In the "modern times" story line, Keaton is a poor man yearning for Leahy, who has rich parents. Leahy's mother, unimpressed with Keaton's bank account but interested in Beery's, decides on Beery as a match for her daughter. Keaton accidentally gets drunk at a restaurant where Beery and Leahy are dining, and Beery tricks the male half of another couple into punching Keaton, who stumbles home drunk. Later, Keaton impresses Leahy by playing a football game, whereas Beery is only a coach; Beery decides to play opposite Keaton. Keaton is overwhelmed by the bigger Beery, but ends up winning the game with an impressive touchdown. An irritated Beery frames Keaton for possession of alcohol and gets him arrested, simultaneously showing him a wedding announcement between him and Leahy — Keaton will be unable to stop the wedding while in jail. While shadowed by a guard, Keaton finds a criminal file showing that Beery has been charged with bigamy and forgery. He attempts to call Leahy to warn her. He accidentally escapes when the phone booth he's using is taken out for replacement. Keaton evades the police chasing him and make it to the church on time, dragging Leahy away from the wedding and into a cab. After showing her Beery's criminal file, he takes Leahy home and prepares to leave, but she kisses him. He declares to the cab driver that they're going back to the church. In the epilogue, they also go out for a walk — this time with their dog instead of children.
Pulito: three plots in three different historical periodsprehistoric times ancient rome and modern times the roaring twentiesare intercut to prove the point that mans love for woman has not significantly changed throughout history in all three plots characters played by the small and slight buster keaton and handsome bruiser wallace beery compete for the attention of the same woman played by margaret leahy each plot follows similar arcs in the story line in which keatons character works for his beloveds attention and eventually wins her over
in the stone age story line keaton competes with the bigger brutish beery for a cavewoman leahy after observing another caveman drag away a woman by the hair in order to claim her keaton tries to become more assertive but is continuously pushed back and bullied by beery an attempt to make leahy jealous by flirting with another woman ends in failure nevertheless keaton grows closer to leahy and beery challenges him to a fight at sunrise keaton wins thanks to hiding a rock in his club but is caught and tied to the tail of an elephant to be dragged around the dirt as punishment upon his return he finds leahy about to be claimed by beery and attempts to make off with her beery catches him and the two battle by tossing boulders at each other from afar with keaton and leahy on a cliff together when beery climbs up to reclaim leahy keaton dispatches leahys cronies and finally defeats him he drags a smitten leahy off by the hair in the epilogue they go off for a walk with their huge family of children following them
in the ancient rome segment keaton attempts to attract the attention of the wealthy leahy but is continually pushed back by beery beery challenges him to a chariot race after a hard snow  keaton wins by using sled dogs instead of horses in revenge beery forces him into the lion pit belonging to leahys family keaton survives by befriending the lion and cleaning its claws keaton is rescued by leahys parents while beery kidnaps leahy keaton rescues her and tries to seduce her in her palanquin which takes off without them in the epilogue they also go out for a walk with many children in tow
in the modern times story line keaton is a poor man yearning for leahy who has rich parents leahys mother unimpressed with keatons bank account but interested in beerys decides on beery as a match for her daughter keaton accidentally gets drunk at a restaurant where beery and leahy are dining and beery tricks the male half of another couple into punching keaton who stumbles home drunk later keaton impresses leahy by playing a football game whereas beery is only a coach beery decides to play opposite keaton keaton is overwhelmed by the bigger beery but ends up winning the game with an impressive touchdown an irritated beery frames keaton for possession of alcohol and gets him arrested simultaneously showing him a wedding announcement between him and leahy  keaton will be unable to stop the wedding while in jail while shadowed by a guard keaton finds a criminal file showing that beery has been charged with bigamy and forgery he attempts to call leahy to warn her he accidentally escapes when the phone booth hes using is taken out for replacement keaton evades the police chasing him and make it to the church on time dragging leahy away from the wedding and into a cab after showing her beerys criminal file he takes leahy home and prepares to leave but she kisses him he declares to the cab driver that theyre going back to the church in the epilogue they also go out for a walk  this time with their dog instead of children

Plot 2:

Originale: A Canadian mother and businesswoman Dinah Middleton (Keane) is devastated when her teenage son, Alex (Anderson), is killed by a hit-and-run driver. When the police fail to turn up any suspects, she turns private detective to track the killer down. She traces the murderer to New York City, only to discover that the crime is not covered by the extradition treaty between Canada and the US. She becomes obsessed with bringing the criminal to justice.
Pulito: a canadian mother and businesswoman dinah middleton keane is devastated when her teenage son alex anderson is killed by a hitandrun driver when the police fail to turn up any suspects she turns private detective to track the killer down she traces the murderer to new york city only to discover that the crime is not covered by the extradition treaty between canada and the us she becomes obsessed with bringing the criminal to justice

Plot 3:

Originale: At the Yucca Mountain nuclear waste repository, a teenage hacker boy named Jesse is caught trying to steal dynamite. His uncle bails him out, and a workman teaches him how to operate a forklift. That night, an animal appears at the repository's mess hall and kills everyone but Jesse. When communications from the repository cease, a group of technicians and scientists are called on to investigate. The facility, once a uranium mine, laboratory, and refinery, has become a classified government facility. The investigators find the place deserted; three go to the control room to try to reboot the computer system, while the other three form a search party. They locate Jesse, catatonic and in a state of shock.
They take him back to the control room and demand answers from Major Tom McQuade, the head of the mission, who evades their questions. When they demand to leave, he orders them back to work, despite their continuing problems with the communications equipment. The main crew heads down to a lower level to investigate the situation while the pilot, Galloway and computer expert Moses stay in the control center with Jesse. On the lower level, the crew gets more and more suspicious but McQuade continues to act as if he knows nothing. When an animal drags Kahane down a tunnel and kills him, the crew flee back to the control room, realizing that McQuade had been up to something after all. Jesse, listening to their radio chatter, realizes what happened and flees the room just before a Velociraptor appears and eats Moses. Galloway flees to the helicopter and starts it up. Before the crew can reach her, a Velociraptor in the back seat attacks her. Galloway loses control and crashes the chopper, stranding the crew.
The group returns to the control room, kept safe by heavy metal doors. There, they learn of the dinosaur's origins from McQuade: a brilliant genetic scientist working for a poultry company went mad and decided to wipe out all of humanity by using a virus made from prehistoric DNA to impregnate first the birds, then human females with dinosaurs. The government narrowly contained the situation, but kept some of the eggs for analysis, storing them in the plant to be hidden. The eggs hatched and killed off the entire crew, and the electrical damage is putting the plant at risk of meltdown. McQuade organized the mission to prevent the meltdown and save the dinosaurs for research. The crew, unsympathetic to McQuade, decide to blow up the dinosaurs with dynamite. McQuade chases after them but is beaten in a brief fight. McQuade explains that he was trying to stop them from going into the facility's lower levels, because radiation from secretly stored nuclear waste and warheads is leaking out and the containment will eventually fail completely.
Jesse devises a plan to crash the computers to send the site into emergency mode, which should get an evacuation squad to come and rescue them. Once the plan is put into place, the group begins making its way back to the surface. They continue using dynamite to hold off any dinosaurs while getting to the elevator. A raptor breaks into the elevator and eats Rawling. Monk and McQuade are injured and blow themselves up to kill the remaining raptors.
Jesse and Jack, now on their own, continue making their way up. Jack, however, has taken a long fall and is injured. Jesse runs outside to find the evacuation team waiting. He tries to get them to go back for Jack, but they refuse, so he runs back in himself and encounters a Tyrannosaurus. Jesse helps Jack get to the rescue helicopter, just as the T. rex bursts out and bites the head off one of the rescue crew. Jesse runs back again, and gets in the forklift. Using the forklift remote, he opens the door to the elevator shaft and wrestles the dinosaur with the forklift, eventually weakening it enough to push it down the shaft. Jesse and Jack are flown off, and Jesse uses a remote detonator to detonate the rest of the dynamite, destroying the facility and preventing a meltdown.
Pulito: at the yucca mountain nuclear waste repository a teenage hacker boy named jesse is caught trying to steal dynamite his uncle bails him out and a workman teaches him how to operate a forklift that night an animal appears at the repositorys mess hall and kills everyone but jesse when communications from the repository cease a group of technicians and scientists are called on to investigate the facility once a uranium mine laboratory and refinery has become a classified government facility the investigators find the place deserted three go to the control room to try to reboot the computer system while the other three form a search party they locate jesse catatonic and in a state of shock
they take him back to the control room and demand answers from major tom mcquade the head of the mission who evades their questions when they demand to leave he orders them back to work despite their continuing problems with the communications equipment the main crew heads down to a lower level to investigate the situation while the pilot galloway and computer expert moses stay in the control center with jesse on the lower level the crew gets more and more suspicious but mcquade continues to act as if he knows nothing when an animal drags kahane down a tunnel and kills him the crew flee back to the control room realizing that mcquade had been up to something after all jesse listening to their radio chatter realizes what happened and flees the room just before a velociraptor appears and eats moses galloway flees to the helicopter and starts it up before the crew can reach her a velociraptor in the back seat attacks her galloway loses control and crashes the chopper stranding the crew
the group returns to the control room kept safe by heavy metal doors there they learn of the dinosaurs origins from mcquade a brilliant genetic scientist working for a poultry company went mad and decided to wipe out all of humanity by using a virus made from prehistoric dna to impregnate first the birds then human females with dinosaurs the government narrowly contained the situation but kept some of the eggs for analysis storing them in the plant to be hidden the eggs hatched and killed off the entire crew and the electrical damage is putting the plant at risk of meltdown mcquade organized the mission to prevent the meltdown and save the dinosaurs for research the crew unsympathetic to mcquade decide to blow up the dinosaurs with dynamite mcquade chases after them but is beaten in a brief fight mcquade explains that he was trying to stop them from going into the facilitys lower levels because radiation from secretly stored nuclear waste and warheads is leaking out and the containment will eventually fail completely
jesse devises a plan to crash the computers to send the site into emergency mode which should get an evacuation squad to come and rescue them once the plan is put into place the group begins making its way back to the surface they continue using dynamite to hold off any dinosaurs while getting to the elevator a raptor breaks into the elevator and eats rawling monk and mcquade are injured and blow themselves up to kill the remaining raptors
jesse and jack now on their own continue making their way up jack however has taken a long fall and is injured jesse runs outside to find the evacuation team waiting he tries to get them to go back for jack but they refuse so he runs back in himself and encounters a tyrannosaurus jesse helps jack get to the rescue helicopter just as the t rex bursts out and bites the head off one of the rescue crew jesse runs back again and gets in the forklift using the forklift remote he opens the door to the elevator shaft and wrestles the dinosaur with the forklift eventually weakening it enough to push it down the shaft jesse and jack are flown off and jesse uses a remote detonator to detonate the rest of the dynamite destroying the facility and preventing a meltdown

str

In [9]:
# Applico la funzione
#df_bilanciato['Cleaned_Plot'] = df_bilanciato['Plot'].apply(pulisci_testo)
#df_pulito = df_bilanciato[['Genre','Cleaned_Plot']]
df_sporco = df_bilanciato[['Genre','Plot']]
df_sporco

       Genre                                               Plot
0     comedy  Sir Sidney Ruff-Diamond (Sid James) is Queen V...
1     comedy  Three plots in three different historical peri...
2      drama  A Canadian mother and businesswoman Dinah Midd...
3     horror  At the Yucca Mountain nuclear waste repository...
4     comedy  Leonard Hoffman is a Los Angeles insurance age...
...      ...                                                ...
4393  horror  William Edward "Billy" Lenz, a boy born with s...
4394  action  Alcoholic U.S. Air Marshal Bill Marks boards a...
4395   drama  Judge Ross, on the Federal Bench, rules in fav...
4396  horror  A year later in 1906, following the events of ...
4397  action  The story revolves around an ego clash between...

[4398 rows x 2 columns]

In [108]:
df_pulito.to_csv('datasetpronto.csv', index=False)

In [10]:
df_sporco.to_csv('datasetsporcopronto.csv', index=False)